#!/usr/bin/env ruby
$: << File.expand_path('lib')

require 'cl'

class Base < Cl::Cmd
  abstract
end

class Add < Base
  def run
    puts 'Success'
  end
end

Cl.new('owners').run(%w(add))

# Output:
#
#   Success

Cl.new('owners').run(%w(base))

# Output:
#
#   Unknown command: base
