#!/usr/bin/env ruby
$: << File.expand_path('lib')

require 'cl'

class Add < Cl::Cmd
  register :add

  arg :owner

  def run
    p owner: owner
  end
end

Cl.new('owners').run(%w(add one))

# Output:
#
#   {:owner=>"one"}
