#!/usr/bin/env ruby
$: << File.expand_path('lib')

require 'cl'

class Add < Cl::Cmd
  register :add

  opt '--to GROUP', downcase: true

  def run
    p to: to
  end
end

Cl.new('owners').run(%w(add --to ONE))

# Output:
#
#   {:to=>"one"}
