#!/usr/bin/env ruby
$: << File.expand_path('lib')

require 'cl'

require 'cl'

class Add < Cl::Cmd
  register :add

  opt '--to GROUP'
  opt '--hidden', internal: true
end

Cl.new('owners').run(%w(add --help))

# Output:
#
#   Usage: owners add [options]
#
#   Options:
#
#     --to GROUP      type: string
#     --help          Get help on this command
