#!/usr/bin/env ruby
$: << File.expand_path('lib')

require 'cl'

class Add < Cl::Cmd
  opt '--to GROUP', note: 'needs to be a group'
end

Cl.new('owners').run(%w(add --help))

# Usage: owners add [options]
#
# Options:
#
#   --to GROUP      type: string, note: needs to be a group
#   --help          Get help on this command
