#!/usr/bin/env ruby
$: << File.expand_path('lib')

module Cmd
  class One < Cl::Cmd
    register :one
  end

  class Two < Cl::Cmd
    register :two
  end
end

p Cl::Cmd[:one] # => Cmd::One
p Cl::Cmd[:two] # => Cmd::Two
