#!/usr/bin/env ruby
$: << File.expand_path('lib')

require 'cl'

class Add < Cl::Cmd
  opt '--to GROUP'
  opt '--password PASS', secret: true

  def run
    puts [:secret?, self.class.opts[:password].secret?].join(' ')
    puts [:tainted?, password.tainted?].join(' ')
  end
end

Cl.new('owners').run(%w(add --password pass))

# Output:
#
#   secret? true
#   tainted? true
